### ISSUE TITLE
Trigger returns 500 

### ISSUE THREAD

**Issue by dmitrii-cernev** [go-vikunja/n8n-vikunja-nodes#122]
Hi, I am trying to connect this module to my n8n instance, however when I try to test the trigger(any of them) - I receive error message `Vikunja Trigger: Internal Server Error`. When I check logs in Vikunja it shows `Struct is invalid. Invalid Data`.

**Comment by kolaente** [comment]
Which Vikunja and n8n version are you using?

**Comment by dmitrii-cernev** [comment]
my bad, the issue was not with Vikunja node but rather with how I set up n8n. I run it locally, and instead of providing full url(with `https://`) I only provided just host. This broke the webhooks and vikunja couldn't be triggered properly. 
Anyway, thanks @kolaente for fast quick reply!
