### ISSUE TITLE
Issue with n8n task update node

### ISSUE THREAD

**Issue by MoonKek** [go-vikunja/n8n-vikunja-nodes#2]
Hello,

I'm having trouble with this particular node in n8n, updating tasks. it seems like no values are being updated. for example if i want to change the priority and mark it as done, it doesn't work. any help would be appreciated, thank you.

![Untitled](https://github.com/go-vikunja/n8n-vikunja-nodes/assets/114215735/51a12c40-47ae-4634-833a-6aa6d0276bee)

vikunja (docker) ver: 0.23.0 - API Token (All permissons allowed)
n8n (docker) ver: 1.27.2
n8n-nodes-vikunja ver: 0.1.1

**Comment by kolaente** [comment]
Are the tasks not updated at all or does the response only indicate they aren't? Can you check the task in Vikunja?

**Comment by MikeyC3040** [comment]
I'm also having issues updating a task. If I'm not mistaken the 'Update' property is currently has the method as GET vs POST called out in the API docs.
`{
    name: 'Update',
    value: 'update',
    description: 'Update a task',
    action: 'Update a task',
    routing: {
	    request: {
		    method: 'GET',
		    url: '=/tasks/{{$parameter.taskId}}',
	    },
    },
},`

**Comment by kolaente** [comment]
I've just released 0.1.2 with a fix. Please update the node in your instance and try again.
