### ISSUE TITLE
Update Task bucket_id

### ISSUE THREAD

**Issue by djagoo** [go-vikunja/n8n-vikunja-nodes#45]
I want to move a task to another project and another bucket based on the bucket it was moved to on the update trigger.

So I created a switch for the 3 bucket_ids in my inbox-project but I cannot update project/bucket_id is there a workaround for this or do I have to wait for it getting implemented?

**Comment by kolaente** [comment]
Which Vikunja version are you using?

**Comment by kolaente** [comment]
It sounds like a bug, but I did't try it out. Since the views will change in the next release, the behaviour here needs adjustments as well. I'll keep that in mind while fixing it.

**Comment by djagoo** [comment]
I explained it very bad sorry. I think it's not a bug but not implemented yet. I want to move a task to another bucket in another project. I just don't find an action in n8n-nodes-vikunja allowing me to do so. Even the action "Update Task" just lets me update for example the title or due date... but not the bucket.

**Comment by kolaente** [comment]
This was implemented in https://github.com/go-vikunja/n8n-vikunja-nodes/commit/683cc599fd6d28cb4f3eb4b6260925813c80a913. I'll release a new version of this package shortly, but it will contain breaking changes for the next Vikunja release - that means you'll need to run an unstable build until the stable version is released to use it with this node.

**Comment by djagoo** [comment]
Thank you very much, I'll give it a try.
