### ISSUE TITLE
Cannot add API Key in n8n

### ISSUE THREAD

**Issue by Niskeletor** [go-vikunja/n8n-vikunja-nodes#52]
Hi!

I'm trying to add my current token in n8n self-hosted, but I cannot add the token through the Workflow or Credentials sections.

I installed it manually and through the GUI. The Vikunja option appears in the Workflow, but the token cannot be added.

I tried restarting Docker and using versions 1.41.0 and 1.42.0, but the issue persists.

![issue vkunja](https://github.com/go-vikunja/n8n-vikunja-nodes/assets/97298802/ac58b3b5-8a80-4b80-a736-987f38b91272)
![issue vkunja2](https://github.com/go-vikunja/n8n-vikunja-nodes/assets/97298802/29af2301-7ef3-4b53-a637-cb358a777a35)

**Comment by kolaente** [comment]
Does it show up if you search for "Vikinja" in the cl"add new credential Dialoge"?

**Comment by kolaente** [comment]
My bad, wrote the comment while on the go :)

Not sure why that's the case. Since it works fine in general, I guess this is a problem with n8n. Can you verify the Vikunja nodes package was installed correctly?

**Comment by querylab** [comment]
I am facing the same problem after installing version 1.41.0. I am not able to add Vikunja API key exactly as shown in the image from @Niskeletor

**Comment by Niskeletor** [comment]
![image](https://github.com/go-vikunja/n8n-vikunja-nodes/assets/97298802/b4546dd4-7864-4545-b633-8b45bd509185)
Yes, I have made sure it will be installed, through GUI and . It is strange, because if nobody has reported any issue I will try to check my n8n instance.

**Comment by kolaente** [comment]
I've just published a new version with updated dependencies. Does it work if you upgrade to 0.1.3?

**Comment by Niskeletor** [comment]
Wow, now it appears! 
I just tested it and it works correctly.

I have also done a couple of Get tests and it shows me the information.

I am very grateful, I must admit that I love Vikunja's project, I hope I can contribute to the development with you in the near future.

![image](https://github.com/go-vikunja/n8n-vikunja-nodes/assets/97298802/d1728bea-9d91-4580-af5b-9e7e7d23a5e6)

**Comment by kolaente** [comment]
I guess I need to get into the habit of publishing these more often 🤓
