### ISSUE TITLE
UnrecognizedNodeTypeError after update.

### ISSUE THREAD

**Issue by harleckinz** [go-vikunja/n8n-vikunja-nodes#53]
Hi!

I just updated the node and ran into this issue. 

"UnrecognizedNodeTypeError: Unrecognized node type: n8n-nodes-vikunja.Vikunja"." The node stopped operating, but still visible and can be added. 

Can I roll back to the previous version somehow?

Thanks!

**Comment by harleckinz** [comment]
I rolled back to n8n-nodes-vikunja@0.1.2 which fixed my workflows and Vikunja nodes, but in the Community packages still shows an error.

![Screenshot 2024-05-16 at 10-56-18 n8n - ▶️ vikunja troublesolving](https://github.com/go-vikunja/n8n-vikunja-nodes/assets/25708009/7e7a2838-c758-4fa9-a6a5-67f0f191fd3a)

**Comment by kolaente** [comment]
Does it show the same error as before?

**Comment by kolaente** [comment]
Closing as inactive, please ping or open a new issue with relevant information if you still have this problem.
