### ISSUE TITLE
Node disappears on restart and credentials not available.

### ISSUE THREAD

**Issue by cmplxshdw** [go-vikunja/n8n-vikunja-nodes#80]
Have tried multiple versions on n8n have gone back to 1.47.2

The issue is:
- The credentials will not show in the credentials. 
- upon restart the vikunja node disappears.

Not sure if I did this correctly. Let me know if you need any more information.

**Comment by k4j8** [comment]
@cmplxshdw, how were you able to resolve this issue? I'm tried n8n versions 1.9.3, 1.47.3, and 1.48.3 and n8n-nodes-vikunja version 0.2.0, always with the same issue. Sometimes the Vikunja node is shown right after installing n8n-nodes-vikunja but then it disappears.

![image](https://github.com/go-vikunja/n8n-vikunja-nodes/assets/7908653/627f6608-1c2f-4641-afc5-1681d78e9996)

**Comment by k4j8** [comment]
Never mind, I figured it out: it's a browser cache issue. Clearing the cache, using a new browser, or opening a private browsing window fixes it.

Credit goes to this tread for finding the solution: https://community.n8n.io/t/issue-with-credentials-for-community-nodes-on-self-hosted/46537.
